"object"!==typeof JSON2&&(JSON2={});
(function(){function b(b){return 10>b?"0"+b:b}function d(b){f.lastIndex=0;return f.test(b)?'"'+b.replace(f,function(b){var c=s[b];return"string"===typeof c?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function c(f,g){var q,y,C,w,t=h,D,F=g[f];F&&"object"===typeof F&&(q=F,C=Object.prototype.toString.apply(q),F="[object Date]"===C?isFinite(q.valueOf())?q.getUTCFullYear()+"-"+b(q.getUTCMonth()+1)+"-"+b(q.getUTCDate())+"T"+b(q.getUTCHours())+":"+b(q.getUTCMinutes())+":"+b(q.getUTCSeconds())+
"Z":null:"[object String]"===C||"[object Number]"===C||"[object Boolean]"===C?q.valueOf():"[object Array]"!==C&&"function"===typeof q.toJSON?q.toJSON(f):q);"function"===typeof v&&(F=v.call(g,f,F));switch(typeof F){case "string":return d(F);case "number":return isFinite(F)?String(F):"null";case "boolean":case "null":return String(F);case "object":if(!F)return"null";h+=x;D=[];if("[object Array]"===Object.prototype.toString.apply(F)){w=F.length;for(q=0;q<w;q+=1)D[q]=c(q,F)||"null";C=0===D.length?"[]":
h?"[\n"+h+D.join(",\n"+h)+"\n"+t+"]":"["+D.join(",")+"]";h=t;return C}if(v&&"object"===typeof v)for(w=v.length,q=0;q<w;q+=1)"string"===typeof v[q]&&(y=v[q],(C=c(y,F))&&D.push(d(y)+(h?": ":":")+C));else for(y in F)Object.prototype.hasOwnProperty.call(F,y)&&(C=c(y,F))&&D.push(d(y)+(h?": ":":")+C);C=0===D.length?"{}":h?"{\n"+h+D.join(",\n"+h)+"\n"+t+"}":"{"+D.join(",")+"}";h=t;return C}}var g=RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
"g"),f=RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]',"g"),h,x,s={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,d,f){var y;x=h="";if("number"===typeof f)for(y=0;y<f;y+=1)x+=" ";else"string"===typeof f&&(x=f);if((v=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON2.stringify");
return c("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,d){function c(b,f){var g,y,h=b[f];if(h&&"object"===typeof h)for(g in h)Object.prototype.hasOwnProperty.call(h,g)&&(y=c(h,g),void 0!==y?h[g]=y:delete h[g]);return d.call(b,f,h)}var f;b=String(b);g.lastIndex=0;g.test(b)&&(b=b.replace(g,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return f=eval("("+b+")"),"function"===typeof d?c({"":f},""):f;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paqAnts&&(_paqAnts=[]);
"object"!==typeof PiwikAnts&&(PiwikAnts=function(){function b(a){return"undefined"!==typeof a}function d(a){return"function"===typeof a}function c(a){return"object"===typeof a}function g(a){return"string"===typeof a||a instanceof String}function f(){var a,b,u;for(a=0;a<arguments.length;a+=1)u=arguments[a],b=u.shift(),g(b)?ea[b].apply(ea,u):b.apply(ea,u)}function h(a,b,u,p){if(a.addEventListener)return a.addEventListener(b,u,p),!0;if(a.attachEvent)return a.attachEvent("on"+b,u);a["on"+b]=u}function x(a,
b){var u="",p,c;for(p in qa)Object.prototype.hasOwnProperty.call(qa,p)&&(c=qa[p][a],d(c)&&(u+=c(b)));return u}function s(){var a;if(!ja)for(ja=!0,x("load"),a=0;a<Ma.length;a++)Ma[a]();return!0}function v(a,b){var u=n.createElement("script");u.type="text/javascript";u.src=a;u.readyState?u.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)u.onreadystatechange=null,b()}:u.onload=b;n.getElementsByTagName("head")[0].appendChild(u)}function S(){var a="";try{a=l.top.document.referrer}catch(b){if(l.parent)try{a=
l.parent.document.referrer}catch(u){a=""}}""===a&&(a=n.referrer);return a}function Q(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function q(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function y(a,b){var u=RegExp("[\\?\x26#]"+b+"\x3d([^\x26#]*)").exec(a);return u?ya(u[1]):""}function C(a){var b=function(a,b){return a<<b|a>>>32-b},u=function(a){var b="",e,c;for(e=7;0<=e;e--)c=a>>>4*e&15,b+=c.toString(16);return b},p,c,d=[],f=1732584193,g=4023233417,y=2562383102,h=
271733878,C=3285377520,t,k,w,n,l,D=[];a=gb(E(a));t=a.length;for(p=0;p<t-3;p+=4)c=a.charCodeAt(p)<<24|a.charCodeAt(p+1)<<16|a.charCodeAt(p+2)<<8|a.charCodeAt(p+3),D.push(c);switch(t&3){case 0:p=2147483648;break;case 1:p=a.charCodeAt(t-1)<<24|8388608;break;case 2:p=a.charCodeAt(t-2)<<24|a.charCodeAt(t-1)<<16|32768;break;case 3:p=a.charCodeAt(t-3)<<24|a.charCodeAt(t-2)<<16|a.charCodeAt(t-1)<<8|128}for(D.push(p);14!==(D.length&15);)D.push(0);D.push(t>>>29);D.push(t<<3&4294967295);for(a=0;a<D.length;a+=
16){for(p=0;16>p;p++)d[p]=D[a+p];for(p=16;79>=p;p++)d[p]=b(d[p-3]^d[p-8]^d[p-14]^d[p-16],1);c=f;t=g;k=y;w=h;n=C;for(p=0;19>=p;p++)l=b(c,5)+(t&k|~t&w)+n+d[p]+1518500249&4294967295,n=w,w=k,k=b(t,30),t=c,c=l;for(p=20;39>=p;p++)l=b(c,5)+(t^k^w)+n+d[p]+1859775393&4294967295,n=w,w=k,k=b(t,30),t=c,c=l;for(p=40;59>=p;p++)l=b(c,5)+(t&k|t&w|k&w)+n+d[p]+2400959708&4294967295,n=w,w=k,k=b(t,30),t=c,c=l;for(p=60;79>=p;p++)l=b(c,5)+(t^k^w)+n+d[p]+3395469782&4294967295,n=w,w=k,k=b(t,30),t=c,c=l;f=f+c&4294967295;
g=g+t&4294967295;y=y+k&4294967295;h=h+w&4294967295;C=C+n&4294967295}l=u(f)+u(g)+u(y)+u(h)+u(C);return l.toLowerCase()}function w(a,b,c){if("translate.googleusercontent.com"===a)""===c&&(c=b),b=y(b,"u"),a=q(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=n.links[0].href,a=q(b);return[a,b,c]}function t(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function D(a){a=a&&a.text?a.text:a;if(!g(a)){var e=n.getElementsByTagName("title");
e&&b(e[0])&&(a=e[0].text)}return a}function F(a){return a?!b(a.children)&&b(a.childNodes)||b(a.children)?a.children:[]:[]}function R(a,e){if(a&&a.indexOf)return a.indexOf(e);if(!b(a)||null===a||!a.length)return-1;var c=a.length;if(0===c)return-1;for(var d=0;d<c;){if(a[d]===e)return d;d++}return-1}function hb(a){function e(a,b){if(l.getComputedStyle)return n.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function c(d,f,g,y,h,C,t){var k=d.parentNode,w;a:{for(w=d.parentNode;w;){if(w===
n){w=!0;break a}w=w.parentNode}w=!1}if(!w)return!1;if(9===k.nodeType)return!0;if("0"===e(d,"opacity")||"none"===e(d,"display")||"hidden"===e(d,"visibility"))return!1;b(f)&&b(g)&&b(y)&&b(h)&&b(C)&&b(t)||(f=d.offsetTop,h=d.offsetLeft,y=f+d.offsetHeight,g=h+d.offsetWidth,C=d.offsetWidth,t=d.offsetHeight);if(a===d&&(0===t||0===C)&&"hidden"===e(d,"overflow"))return!1;if(k){if("hidden"===e(k,"overflow")||"scroll"===e(k,"overflow"))if(h+1>k.offsetWidth+k.scrollLeft||h+C-1<k.scrollLeft||f+1>k.offsetHeight+
k.scrollTop||f+t-1<k.scrollTop)return!1;d.offsetParent===k&&(h+=k.offsetLeft,f+=k.offsetTop);return c(k,f,g,y,h,C,t)}return!0}return a?c(a):!1}function fa(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function r(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(n.referrer);if(b){if(b[1]!==String(a))return!1;l.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=l.name.split("###");return 3===a.length&&"Piwik_Overlay"===
a[0]}function z(a,b,c){var d=l.name.split("###"),f=d[1],g=d[2],y=fa(a,b);v(y+"plugins/Overlay/client/client.js?v\x3d1",function(){Piwik_Overlay_Client.initialize(y,c,f,g)})}function ka(a,e){function f(m,a,b,e,c,d){if(!ba){var u;b&&(u=new Date,u.setTime(u.getTime()+b));n.cookie=m+"\x3d"+E(a)+(b?";expires\x3d"+u.toGMTString():"")+";path\x3d"+(e||"/")+(c?";domain\x3d"+c:"")+(d?";secure":"")}}function p(m){return ba?0:(m=RegExp("(^|;)[ ]*"+m+"\x3d([^;]*)").exec(n.cookie))?ya(m[2]):0}function aa(m){var a;
return ib?(a=/#.*/,m.replace(a,"")):m}function F(m){var a,b,e;for(a=0;a<Aa.length;a++){b=t(Aa[a].toLowerCase());if(m===b)return!0;if("."===b.slice(0,1)){if(m===b.slice(1))return!0;e=m.length-b.length;if(0<e&&m.slice(e)===b)return!0}}return!1}function s(m,a,b){b=!0;"undefined"==typeof a||a||(b=!1);a=document.createElement("script");a.type="text/javascript";a.async=b;a.src=V+(0>V.indexOf("?")?"?":"\x26")+m;a.onload=function(){};m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(a,
m)}function R(m,a,B){b(B)&&null!==B||(B=!0);try{var e=l.XMLHttpRequest?new l.XMLHttpRequest:l.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;e.open("POST",V,!0);e.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!B?"function"===typeof a&&a():s(m,!0,a)};e.setRequestHeader("Content-Type",jb);e.send(m)}catch(c){B&&s(m,!0,a)}}function v(m){m=(new Date).getTime()+m;if(!Z||m>Z)Z=m}function L(m){var a=(new Date).getTime();ga&&a<ga?(a=ga-a,setTimeout(m,a),v(a+
50),ga+=50):(!1===ga&&(ga=a+800),m())}function T(m,a,b,e){!Ba&&m&&L(function(){"POST"===kb?R(m,e):s(m,b,e);v(a)})}function fa(m,a){var b;b=Ba?!1:m&&m.length;if(b){var e='{"requests":["?'+m.join('","?')+'"]}';L(function(){R(e,null,!1);v(a)})}}function M(m){return lb+m+"."+O+"."+mb}function ea(){if(ba)return"0";if(!b(H.cookieEnabled)){var m=M("testcookie");f(m,"1");return"1"===p(m)?"1":"0"}return H.cookieEnabled?"1":"0"}function $(){mb=Oa((W||Pa)+(X||"/")).slice(0,4)}function ka(){var m=M("cvar"),m=
p(m);return m.length&&(m=JSON2.parse(m),c(m))?m:{}}function N(){Qa=(new Date).getTime()}function oa(){var m=new Date,a=Math.round(m.getTime()/1E3),b=M("id");return(b=p(b))?(m=b.split("."),m.unshift("0"),ra.length&&(m[1]=ra),m):m=["1",ra.length?ra:Oa((H.userAgent||"")+(H.platform||"")+JSON2.stringify(Y)+m.getTime()+Math.random()).slice(0,16),a,0,a,"",""]}function za(){var m=oa(),a=m[0],B=m[1],e=m[2],c=m[3],d=m[4],f=m[5];b(m[6])||(m[6]="");return{newVisitor:a,uuid:B,createTs:e,visitCount:c,currentVisitTs:d,
lastVisitTs:f,lastEcommerceOrderTs:m[6]}}function pa(){var m=(new Date).getTime(),a=za().createTs;return 1E3*parseInt(a,10)+Ra-m}function Na(a){if(O){var G=Math.round((new Date).getTime()/1E3);b(a)||(a=za());a=a.uuid+"."+a.createTs+"."+a.visitCount+"."+G+"."+a.lastVisitTs+"."+a.lastEcommerceOrderTs;f(M("id"),a,pa(),X,W)}}function la(){var a=p(M("ref"));if(a.length)try{if(a=JSON2.parse(a),c(a))return a}catch(b){}return["","",0,""]}function nb(){var a=ba;ba=!1;f(M("id"),"",-86400,X,W);f(M("ses"),"",
-86400,X,W);f(M("cvar"),"",-86400,X,W);f(M("ref"),"",-86400,X,W);ba=a}function ob(a){if(a&&c(a)){var b=[],B;for(B in a)Object.prototype.hasOwnProperty.call(a,B)&&b.push(B);B={};b.sort();var e=b.length,d;for(d=0;d<e;d++)B[b[d]]=a[b[d]];return B}}function U(a,G,B,e){function c(a,m){var b=JSON2.stringify(a);return 2<b.length?(b=E(b),""!=b&&(0>b.lastIndexOf("5D%7D")&&b.lastIndexOf("5D%7D")+4!=b.length-1)&&(b+="5D%7D"),"\x26"+m+"\x3d"+b):""}var g,h=new Date,C=Math.round(h.getTime()/1E3),t,k,w,l,D=K,r=
M("ses"),s=M("ref"),A=M("cvar");w=p(r);l=la();var R=Ca||pb,v,z;ba&&nb();if(Ba)return"";r=za();b(e)||(e="");var H=n.characterSet||n.charset;H&&"utf-8"!==H.toLowerCase()||(H=null);v=l[0];z=l[1];t=l[2];k=l[3];if(!w){w=Da/1E3;if(!r.lastVisitTs||C-r.lastVisitTs>w)r.visitCount++,r.lastVisitTs=r.currentVisitTs;if(!Sa||!v.length){for(g in Ea)if(Object.prototype.hasOwnProperty.call(Ea,g)&&(v=y(R,Ea[g]),v.length))break;for(g in Fa)if(Object.prototype.hasOwnProperty.call(Fa,g)&&(z=y(R,Fa[g]),z.length))break}w=
q(sa);l=k.length?q(k):"";!w.length||(F(w)||Sa&&l.length&&!F(l))||(k=sa);if(k.length||v.length)t=C,l=[v,z,t,aa(k.slice(0,100))],f(s,JSON2.stringify(l),qb,X,W)}a+="\x26idsite\x3d"+O+"\x26rec\x3d1\x26r\x3d"+String(Math.random()).slice(2,8)+"\x26h\x3d"+h.getHours()+"\x26m\x3d"+h.getMinutes()+"\x26s\x3d"+h.getSeconds()+"\x26url\x3d"+E(aa(R))+(sa.length?"\x26urlref\x3d"+E(aa(sa)):"")+(ma&&ma.length?"\x26uid\x3d"+E(ma):"")+"\x26_id\x3d"+r.uuid+"\x26_idts\x3d"+r.createTs+"\x26_idvc\x3d"+r.visitCount+"\x26_idn\x3d"+
r.newVisitor+(v.length?"\x26_rcn\x3d"+E(v):"")+(z.length?"\x26_rck\x3d"+E(z):"")+"\x26_refts\x3d"+t+"\x26_viewts\x3d"+r.lastVisitTs+(String(r.lastEcommerceOrderTs).length?"\x26_ects\x3d"+r.lastEcommerceOrderTs:"")+(String(k).length?"\x26_ref\x3d"+E(aa(k.slice(0,100))):"")+(H?"\x26cs\x3d"+E(H):"")+"\x26send_image\x3d0";for(g in Y)Object.prototype.hasOwnProperty.call(Y,g)&&(a+="\x26"+g+"\x3d"+Y[g]);G?a+="\x26data\x3d"+E(JSON2.stringify(G)):ca&&(a+="\x26data\x3d"+E(JSON2.stringify(ca)));G=ob(ha);h=ob(Ta);
a+=c(G,"cvar");a+=c(h,"e_cvar");if(K){a+=c(K,"_cvar");for(g in D)Object.prototype.hasOwnProperty.call(D,g)&&(""!==K[g][0]&&""!==K[g][1]||delete K[g]);rb&&f(A,JSON2.stringify(K),Da,X,W)}sb&&(Ua?a+="\x26gt_ms\x3d"+Ua:ia&&(ia.timing&&ia.timing.requestStart&&ia.timing.responseEnd)&&(a+="\x26gt_ms\x3d"+(ia.timing.responseEnd-ia.timing.requestStart)));r.lastEcommerceOrderTs=b(e)&&String(e).length?e:r.lastEcommerceOrderTs;Na(r);f(M("ses"),"*",Da,X,W);a+=x(B);Va.length&&(a+="\x26"+Va);d(Wa)&&(a=Wa(a));return a}
function tb(a,G,B,e,c,d,f,g){a="idgoal\x3d"+a;var u;g=new Date;var y=[],h;String(G).length&&(a+="\x26ec_id\x3d"+E(G),u=Math.round(g.getTime()/1E3));a+="\x26revenue\x3d"+B;String(e).length&&(a+="\x26ec_st\x3d"+e);String(c).length&&(a+="\x26ec_tx\x3d"+c);String(d).length&&(a+="\x26ec_sh\x3d"+d);String(f).length&&(a+="\x26ec_dt\x3d"+f);if(J){for(h in J)Object.prototype.hasOwnProperty.call(J,h)&&(b(J[h][1])||(J[h][1]=""),b(J[h][2])||(J[h][2]=""),b(J[h][3])&&0!==String(J[h][3]).length||(J[h][3]=0),b(J[h][4])&&
0!==String(J[h][4]).length||(J[h][4]=1),y.push(J[h]));a+="\x26ec_items\x3d"+E(JSON2.stringify(y))}a=U(a,ca,"ecommerce",u);T(a,I,!1)}function Sb(a,b){var B=new Date,e=U("action_name\x3d"+E(D(a||ub)),b,"log");T(e,I,!0);Xa&&(ta&&!vb)&&(vb=!0,h(n,"click",N),h(n,"mouseup",N),h(n,"mousedown",N),h(n,"mousemove",N),h(n,"mousewheel",N),h(l,"DOMMouseScroll",N),h(l,"scroll",N),h(n,"keypress",N),h(n,"keydown",N),h(n,"keyup",N),h(l,"resize",N),h(l,"focus",N),h(l,"blur",N),Qa=B.getTime(),setTimeout(function Qb(){var a;
B=new Date;Qa+ta>B.getTime()&&(Xa<B.getTime()&&(a=U("ping\x3d1",b,"ping"),T(a,I,!0)),setTimeout(Qb,ta))},ta))}function Ya(a,b){var B,e="(^| )(piwik[_-]"+b;if(a)for(B=0;B<a.length;B++)e+="|"+a[B];return RegExp(e+")( |$)")}function ua(a){return V&&a&&0===String(a).indexOf(V)}function Za(a){var G=a;for(a=G.parentNode;null!==a&&b(a)&&!k.isLinkElement(G);)G=a,a=G.parentNode;a=G;if(k.hasNodeAttribute(a,"href")&&b(a.href)&&(G=k.getAttributeValueFromNode(a,"href"),!ua(G))){var G=a.hostname||q(a.href),B=G.toLowerCase(),
G=a.href.replace(G,B);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(G)){a=a.className;B=F(B);if(ua(G))a=0;else{var e=Ya(wb,"download"),c=Ya(xb,"link"),d=RegExp("\\.("+va+")([?\x26#]|$)","i");a=c.test(a)?"link":e.test(a)||d.test(G)?"download":B?0:"link"}if(a)return{type:a,href:G}}}}function wa(a,b,e,c){if(a=A.buildInteractionRequestParams(a,b,e,c))return U(a,null,"contentInteraction")}function yb(a,G,e,c,d){if(b(a)){if(ua(a))return a;var f=A.toAbsoluteUrl(a),f="redirecturl\x3d"+
E(f)+"\x26",f=f+wa(G,e,c,d||a);a="\x26";0>V.indexOf("?")&&(a="?");return V+a+f}}function $a(a,b){if(!a||!b)return!1;var e=A.findTargetNode(a);if(A.shouldIgnoreInteraction(e))return!1;e=A.findTargetNodeNoDefault(a);return!e||e&&b&&(e.contains?e.contains(b):e===b||e.compareDocumentPosition&&e.compareDocumentPosition(b)&16)?!0:!1}function zb(a,b,e){if(a){var c=A.findParentContentNode(a);if(c&&$a(c,a)&&(a=A.buildContentBlock(c)))return!a.target&&e&&(a.target=e),A.buildInteractionRequestParams(b,a.name,
a.piece,a.target)}}function Ab(a){if(!da||!da.length)return!1;var b,e;for(b=0;b<da.length;b++)if((e=da[b])&&e.name===a.name&&e.piece===a.piece&&e.target===a.target)return!0;return!1}function ab(a){if(!a)return!1;var b=A.findTargetNode(a);if(!b||A.shouldIgnoreInteraction(b))return!1;var e=Za(b);if(bb&&e&&e.type)return!1;if(k.isLinkElement(b)&&k.hasNodeAttributeWithValue(b,"href")){e=String(k.getAttributeValueFromNode(b,"href"));if(0===e.indexOf("#"))return!1;if(ua(e))return!0;if(!A.isUrlToCurrentDomain(e))return!1;
var c=A.buildContentBlock(a);if(!c)return;a=c.name;var d=c.piece,c=c.target;if(!k.hasNodeAttributeWithValue(b,A.CONTENT_TARGET_ATTR)||b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=!0,c=A.toAbsoluteUrl(e),k.setAnyAttribute(b,A.CONTENT_TARGET_ATTR,c);e=yb(e,"click",a,d,c);A.setHrefAttribute(b,e);return!0}return!1}function Bb(a){return function(b){if(a){var e=A.findParentContentNode(a),c;b&&(c=b.target||b.srcElement);c||(c=a);if($a(e,c)){v(I);k.isLinkElement(a)&&(k.hasNodeAttributeWithValue(a,
"href")&&k.hasNodeAttributeWithValue(a,A.CONTENT_TARGET_ATTR))&&(b=k.getAttributeValueFromNode(a,"href"),!ua(b)&&a.wasContentTargetAttrReplaced&&k.setAnyAttribute(a,A.CONTENT_TARGET_ATTR,""));b=Za(a);if(Ga&&b&&b.type)return b.type;if(ab(e))return"href";if(e=A.buildContentBlock(e))return e=wa("click",e.name,e.piece,e.target),T(e,I,!0),e}}}}function Cb(a){if(a&&a.length){var b,e;for(b=0;b<a.length;b++)(e=A.findTargetNode(a[b]))&&!e.contentInteractionTrackingSetupDone&&(e.contentInteractionTrackingSetupDone=
!0,h(e,"click",Bb(e)))}}function Db(a,b){if(!a||!a.length)return[];var e,c;for(e=0;e<a.length;e++)Ab(a[e])?(a.splice(e,1),e--):da.push(a[e]);if(!a||!a.length)return[];if(b&&b.length)for(e=0;e<b.length;e++)ab(b[e]);Cb(b);var d=[];for(e=0;e<a.length;e++)c=U(A.buildImpressionRequestParams(a[e].name,a[e].piece,a[e].target),void 0,"contentImpressions"),d.push(c);return d}function Ha(a){var b=A.collectContent(a);return Db(b,a)}function cb(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)A.isNodeVisible(a[b])||
(a.splice(b,1),b--);return a&&a.length?Ha(a):[]}function Eb(a,b,e){a=A.buildImpressionRequestParams(a,b,e);return U(a,null,"contentImpression")}function Fb(a,b){if(a){var e=A.findParentContentNode(a);if(e=A.buildContentBlock(e))return b||(b="Unknown"),wa(b,e.name,e.piece,e.target)}}function Gb(a,e,c,d,f){if(0===String(a).length||0===String(e).length)return!1;a=U("e_c\x3d"+E(a)+"\x26e_a\x3d"+E(e)+(b(c)?"\x26e_n\x3d"+E(c):"")+(b(d)?"\x26e_v\x3d"+E(d):""),f,"event");T(a,I,!0)}function Hb(a,b,e,c,d){b=
b+"\x3d"+E(aa(a));(a=zb(d,"click",a))&&(b+="\x26"+a);e=U(b,e,"link");T(e,c?0:I,!0,c)}function P(a){var b,e,c=["","webkit","ms","moz"],d;if(!Ib)for(e=0;e<c.length;e++)if(d=c[e],Object.prototype.hasOwnProperty.call(n,""!==d?d+"H"+"hidden".slice(1):"hidden")){"prerender"===n[""!==d?d+"V"+"visibilityState".slice(1):"visibilityState"]&&(b=!0);break}b?h(n,d+"visibilitychange",function Rb(){n.removeEventListener(d+"visibilitychange",Rb,!1);a()}):a()}function Ia(a){"complete"===n.readyState?a():l.addEventListener?
l.addEventListener("load",a):l.attachEvent&&l.attachEvent("onLoad",a)}function db(a){var b=!1;(b=n.attachEvent?"complete"===n.readyState:"loading"!==n.readyState)?a():n.addEventListener?n.addEventListener("DOMContentLoaded",a):n.attachEvent&&n.attachEvent("onreadystatechange",a)}function Jb(a){var b=Za(a);b&&b.type&&(b.href=gb(b.href),Hb(b.href,b.type,void 0,null,a))}function eb(a){var b,e;a=a||l.event;b=a.which||a.button;e=a.target||a.srcElement;"click"===a.type?e&&Jb(e):"mousedown"===a.type?1!==
b&&2!==b||!e?Ja=Ka=null:(Ja=b,Ka=e):"mouseup"===a.type&&(b===Ja&&e===Ka&&Jb(e),Ja=Ka=null)}function Kb(a,b){b?(h(a,"mouseup",eb,!1),h(a,"mousedown",eb,!1)):h(a,"click",eb,!1)}function Lb(a){if(!Ga){Ga=!0;var b,e=Ya(Mb,"ignore"),c=n.links;if(c)for(b=0;b<c.length;b++)e.test(c[b].className)||Kb(c[b],a)}}function Nb(a,b,e){function c(){d=!0}if(na)return!0;na=!0;var d=!1,f,g;Ia(function(){function u(a){setTimeout(function(){na&&(d=!1,e.trackVisibleContentImpressions(),u(a))},a)}function h(a){setTimeout(function(){na&&
(d&&(d=!1,e.trackVisibleContentImpressions()),h(a))},a)}if(a){f=["scroll","resize"];for(g=0;g<f.length;g++)n.addEventListener?n.addEventListener(f[g],c):l.attachEvent("on"+f[g],c);h(100)}b&&0<b&&(b=parseInt(b,10),u(b))})}var La={},fb=w(n.domain,l.location.href,S()),Pa=t(fb[0]),pb=ya(fb[1]),sa=ya(fb[2]),Ob=!1,kb="GET",jb="application/x-www-form-urlencoded; charset\x3dUTF-8",V=a||"",Pb="",Va="",O=e||"",ma="",ra="",Ca,ub=n.title,va="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",
Aa=[Pa],Mb=[],wb=[],xb=[],I=500,Xa,ta,ib,ca,Ea=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],Fa=["pk_kwd","piwik_kwd","utm_term"],lb="_pk_",W,X,ba=!1,Ba,Ib,Sa,Ra=339552E5,Da=18E5,qb=15768E6,sb=!0,Ua=0,rb=!1,K=!1,Wa,ha={},Ta={},J={},Y={},da=[],na=!1,ga=!1,Ga=!1,bb=!1,vb=!1,Qa,Ja,Ka,Oa=C,mb;(function(){var a,e,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},f=/Mac OS X.*Safari\//.test(H.userAgent)?l.devicePixelRatio||1:1;if(!/MSIE/.test(H.userAgent)){if(H.mimeTypes&&H.mimeTypes.length)for(a in c)Object.prototype.hasOwnProperty.call(c,a)&&(e=H.mimeTypes[c[a]],Y[a]=e&&e.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&(b(H.javaEnabled)&&H.javaEnabled())&&(Y.java="1");d(l.GearsFactory)&&(Y.gears="1");Y.cookie=ea()}Y.res=xa.width*f+"x"+xa.height*
f})();$();Na();x("run",function(a,e){var d=null;if(g(a)&&!b(La[a])&&e){if(c(e))d=e;else if(g(e))try{eval("hookObj \x3d"+e)}catch(f){}La[a]=d}return d});return{hook:La,getHook:function(a){return La[a]},getQuery:function(){return k},getContent:function(){return A},buildContentImpressionRequest:Eb,buildContentInteractionRequest:wa,buildContentInteractionRequestNode:Fb,buildContentInteractionTrackingRedirectUrl:yb,getContentImpressionsRequestsFromNodes:Ha,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:cb,
trackCallbackOnLoad:Ia,trackCallbackOnReady:db,buildContentImpressionsRequests:Db,wasContentImpressionAlreadyTracked:Ab,appendContentInteractionToRequestIfPossible:zb,setupInteractionsTracking:Cb,trackContentImpressionClickInteraction:Bb,internalIsNodeVisible:hb,isNodeAuthorizedToTriggerInteraction:$a,replaceHrefIfInternalLink:ab,getConfigDownloadExtensions:function(){return va},enableTrackOnlyVisibleContent:function(a,b){return Nb(a,b,this)},clearTrackedContentImpressions:function(){da=[]},getTrackedContentImpressions:function(){return da},
clearEnableTrackOnlyVisibleContent:function(){na=!1},disableLinkTracking:function(){bb=Ga=!1},getConfigVisitorCookieTimeout:function(){return Ra},getRemainingVisitorCookieTimeout:pa,getVisitorId:function(){return za().uuid},getVisitorInfo:function(){return oa()},getAttributionInfo:function(){return la()},getAttributionCampaignName:function(){return la()[0]},getAttributionCampaignKeyword:function(){return la()[1]},getAttributionReferrerTimestamp:function(){return la()[2]},getAttributionReferrerUrl:function(){return la()[3]},
setTrackerUrl:function(a){V=a},getTrackerUrl:function(){return V},getSiteId:function(){return O},setSiteId:function(a){O=a;Na()},setUserId:function(a){ma=a;ra=Oa(ma).substr(0,16)},getUserId:function(){return ma},setCustomData:function(a,b){c(a)?ca=a:(ca||(ca={}),ca[a]=b)},getCustomData:function(){return ca},setCustomRequestProcessing:function(a){Wa=a},appendToTrackingUrl:function(a){Va=a},getRequest:function(a){return U(a)},addPlugin:function(a,b){qa[a]=b},setCustomVariable:function(a,e,c,d){b(d)||
(d="visit");b(e)&&(b(c)||(c=""),0<a&&(e=g(e)?e:String(e),c=g(c)?c:String(c),e=[e.slice(0,200),c.slice(0,200)],"visit"===d||2===d?(!1===K&&(K=ka()),K[a]=e):"page"===d||3===d?ha[a]=e:"event"===d&&(Ta[a]=e)))},getCustomVariable:function(a,e){var c;b(e)||(e="visit");if("page"===e||3===e)c=ha[a];else if("event"===e)c=Ta[a];else if("visit"===e||2===e)!1===K&&(K=ka()),c=K[a];return!b(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},
storeCustomVariablesInCookie:function(){rb=!0},setLinkTrackingTimer:function(a){I=a},setDownloadExtensions:function(a){va=a},addDownloadExtensions:function(a){va+="|"+a},setDomains:function(a){Aa=g(a)?[a]:a;Aa.push(Pa)},setIgnoreClasses:function(a){Mb=g(a)?[a]:a},setRequestMethod:function(a){kb=a||"GET"},setRequestContentType:function(a){jb=a||"application/x-www-form-urlencoded; charset\x3dUTF-8"},setReferrerUrl:function(a){sa=a},setCustomUrl:function(a){var b=pb,e;Q(a)?Ca=a:"/"===a.slice(0,1)?Ca=
Q(b)+"://"+q(b)+a:(b=aa(b),e=b.indexOf("?"),0<=e&&(b=b.slice(0,e)),e=b.lastIndexOf("/"),e!==b.length-1&&(b=b.slice(0,e+1)),Ca=b+a)},setDocumentTitle:function(a){ub=a},setAPIUrl:function(a){Pb=a},setDownloadClasses:function(a){wb=g(a)?[a]:a},setLinkClasses:function(a){xb=g(a)?[a]:a},setCampaignNameKey:function(a){Ea=g(a)?[a]:a},setCampaignKeywordKey:function(a){Fa=g(a)?[a]:a},discardHashTag:function(a){ib=a},setCookieNamePrefix:function(a){lb=a;K=ka()},setCookieDomain:function(a){W=t(a);$()},setCookiePath:function(a){X=
a;$()},setVisitorCookieTimeout:function(a){Ra=1E3*a},setSessionCookieTimeout:function(a){Da=1E3*a},setReferralCookieTimeout:function(a){qb=1E3*a},setConversionAttributionFirstReferrer:function(a){Sa=a},disableCookies:function(){ba=!0;Y.cookie="0"},deleteCookies:function(){nb()},setDoNotTrack:function(a){var b=H.doNotTrack||H.msDoNotTrack;(Ba=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Kb(a,b)},enableLinkTracking:function(a){bb=!0;ja?Lb(a):Ma.push(function(){Lb(a)})},
enableJSErrorTracking:function(){if(!Ob){Ob=!0;var a=l.onerror;l.onerror=function(b,e,c,d,f){P(function(){var a=e+":"+c;d&&(a+=":"+d);Gb("JavaScript Errors",a,b)});return a?a(b,e,c,d,f):!1}}},disablePerformanceTracking:function(){sb=!1},setGenerationTimeMs:function(a){Ua=parseInt(a,10)},setHeartBeatTimer:function(a,b){Xa=(new Date).getTime()+1E3*a;ta=1E3*b},killFrame:function(){l.location!==l.top.location&&(l.top.location=l.location)},redirectFile:function(a){"file:"===l.location.protocol&&(l.location=
a)},setCountPreRendered:function(a){Ib=a},trackGoal:function(a,b,e){P(function(){var c=U("idgoal\x3d"+a+(b?"\x26revenue\x3d"+b:""),e,"goal");T(c,I,!1)})},trackLink:function(a,b,e,c){P(function(){Hb(a,b,e,c)})},trackPageView:function(a,b){da=[];r(O)?P(function(){z(V,Pb,O)}):P(function(){Sb(a,b)})},trackAllContentImpressions:function(){r(O)||P(function(){db(function(){var a=A.findContentNodes(),a=Ha(a);fa(a,I)})})},trackVisibleContentImpressions:function(a,e){r(O)||(b(a)||(a=!0),b(e)||(e=750),Nb(a,
e,this),P(function(){Ia(function(){var a=A.findContentNodes(),a=cb(a);fa(a,I)})}))},trackContentImpression:function(a,b,e){!r(O)&&a&&(b=b||"Unknown",P(function(){var c=Eb(a,b,e);T(c,I,!0)}))},trackContentImpressionsWithinNode:function(a){!r(O)&&a&&P(function(){na?Ia(function(){var b=A.findContentNodesWithinNode(a),b=cb(b);fa(b,I)}):db(function(){var b=A.findContentNodesWithinNode(a),b=Ha(b);fa(b,I)})})},trackContentInteraction:function(a,b,e,c){!r(O)&&(a&&b)&&(e=e||"Unknown",P(function(){var d=wa(a,
b,e,c);T(d,I,!0)}))},trackContentInteractionNode:function(a,b){!r(O)&&a&&P(function(){var e=Fb(a,b);T(e,I,!0)})},trackEvent:function(a,b,e,c,d){P(function(){Gb(a,b,e,c,d)})},trackSiteSearch:function(a,e,c){P(function(){var d=U("search\x3d"+E(a)+(e?"\x26search_cat\x3d"+E(e):"")+(b(c)?"\x26search_count\x3d"+c:""),void 0,"sitesearch");T(d,I,!0)})},setEcommerceView:function(a,e,c,d){b(c)&&c.length?c instanceof Array&&(c=JSON2.stringify(c)):c="";ha[5]=["_pkc",c];b(d)&&String(d).length&&(ha[2]=["_pkp",
d]);if(b(a)&&a.length||b(e)&&e.length)b(a)&&a.length&&(ha[3]=["_pks",a]),b(e)&&e.length||(e=""),ha[4]=["_pkn",e]},addEcommerceItem:function(a,b,e,c,d){a.length&&(J[a]=[a,b,e,c,d])},trackEcommerceOrder:function(a,e,c,d,f,g,u){String(e).length&&b(c)&&tb(a,e,c,d,f,g,u)},trackEcommerceCartUpdate:function(a){b(a)&&tb("","",a,"","","","","")}}}var Z,qa={},n=document,H=navigator,xa=screen,l=window,ia=l.performance||l.mozPerformance||l.msPerformance||l.webkitPerformance,ja=!1,Ma=[],E=l.encodeURIComponent,
ya=l.decodeURIComponent,gb=unescape,ea,L,oa,k={htmlCollectionToArray:function(a){var b=[],c;if(!a||!a.length)return b;for(c=0;c<a.length;c++)b.push(a[c]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var b,c,d=[];for(b=0;b<a.length;b++)c=this.find(a[b]),d=d.concat(c);return d=this.makeNodesUnique(d)},findNodesByTagName:function(a,b){if(!a||!b||!a.getElementsByTagName)return[];
var c=a.getElementsByTagName(b);return this.htmlCollectionToArray(c)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var d=R(b,a),f=R(b,c);return d===f?0:d>f?-1:1});if(1>=a.length)return a;var c=0,d=0,f=[],g;for(g=a[c++];g;)g===a[c]&&(d=f.push(c)),g=a[c++]||null;for(;d--;)a.splice(f[d],1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;
if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,d=a.attributes;if(d){for(c=0;c<d.length;c++)if(d[c].nodeName===b)return d[c].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,b){if(a&&b&&a.className){var c=a.className.split(" ");if(-1!==R(c,b))return!0}return!1},
findNodesHavingAttribute:function(a,b,c){c||(c=[]);if(!a||!b)return c;a=F(a);if(!a||!a.length)return c;var d,f;for(d=0;d<a.length;d++)f=a[d],this.hasNodeAttribute(f,b)&&c.push(f),c=this.findNodesHavingAttribute(f,b,c);return c},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length)return c[0]}},findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var c=
this.findNodesHavingAttribute(a,b);if(c&&c.length){var d;for(d=0;d<c.length;d++)if(this.getAttributeValueFromNode(c[d],b))return c[d]}}},findNodesHavingCssClass:function(a,b,c){c||(c=[]);if(!a||!b)return c;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=F(a);if(!a||!a.length)return[];var d,f;for(d=0;d<a.length;d++)f=a[d],this.hasNodeCssClass(f,b)&&c.push(f),c=this.findNodesHavingCssClass(f,b,c);return c},findFirstNodeHavingClass:function(a,b){if(a&&
b){if(this.hasNodeCssClass(a,b))return a;var c=this.findNodesHavingCssClass(a,b);if(c&&c.length)return c[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==R(["a","area"],a)},setAnyAttribute:function(a,b,c){a&&b&&(a.setAttribute?a.setAttribute(b,c):a[b]=c)}},A={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",
CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return k.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var b=k.findNodesHavingCssClass(a,this.CONTENT_CLASS),c=k.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(c&&c.length){var d;for(d=0;d<c.length;d++)b.push(c[d])}k.hasNodeAttribute(a,
this.CONTENT_ATTR)?b.push(a):k.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=k.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==n&&a.parentNode;){if(k.hasNodeAttribute(a,this.CONTENT_ATTR)||k.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;(b=k.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(b=k.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=
k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=k.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=k.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(b)return k.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);
if(k.hasNodeAttributeWithValue(a,"title"))return k.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(k.hasNodeAttributeWithValue(b,"title"))return k.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(k.hasNodeAttributeWithValue(a,"title"))return k.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var b=k.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return k.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);
if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(k.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return k.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(k.hasNodeAttributeWithValue(b,"href"))return a=k.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(k.hasNodeAttributeWithValue(a,"href"))return a=k.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||
!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&(a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a))&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=a.nodeName.toLowerCase();if(-1!==R(["img","embed","video","audio"],b)&&k.findFirstNodeHavingAttributeWithValue(a,"src"))return a=k.findFirstNodeHavingAttributeWithValue(a,
"src"),k.getAttributeValueFromNode(a,"src");if("object"===b&&k.hasNodeAttributeWithValue(a,"data"))return k.getAttributeValueFromNode(a,"data");if("object"===b){if((b=k.findNodesByTagName(a,"param"))&&b.length){var c;for(c=0;c<b.length;c++)if("movie"===k.getAttributeValueFromNode(b[c],"name")&&k.hasNodeAttributeWithValue(b[c],"value"))return k.getAttributeValueFromNode(b[c],"value")}if((a=k.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&
String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),c=n.documentElement||{},d=0>b.top;d&&a.offsetTop&&(d=0<a.offsetTop+b.height);a=c.clientWidth;l.innerWidth&&a>l.innerWidth&&(a=l.innerWidth);c=c.clientHeight;l.innerHeight&&c>l.innerHeight&&(c=l.innerHeight);return(0<b.bottom||d)&&0<b.right&&b.left<a&&(b.top<c||d)},isNodeVisible:function(a){var b=hb(a);a=this.isOrWasNodeInViewport(a);
return b&&a},buildInteractionRequestParams:function(a,b,c,d){var f="";a&&(f+="c_i\x3d"+E(a));b&&(f&&(f+="\x26"),f+="c_n\x3d"+E(b));c&&(f&&(f+="\x26"),f+="c_p\x3d"+E(c));d&&(f&&(f+="\x26"),f+="c_t\x3d"+E(d));return f},buildImpressionRequestParams:function(a,b,c){a="c_n\x3d"+E(a)+"\x26c_p\x3d"+E(b);c&&(a+="\x26c_t\x3d"+E(c));return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),c=this.findContentPiece(a);a=this.findContentTarget(a);b=this.trim(b);c=this.trim(c);a=this.trim(a);
return{name:b||"Unknown",piece:c||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],d,f;for(d=0;d<a.length;d++)f=this.buildContentBlock(a[d]),b(f)&&c.push(f);return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||l.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+
a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,
b){a&&b&&k.setAnyAttribute(a,"href",b)},shouldIgnoreInteraction:function(a){var b=k.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=k.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};h(l,"beforeunload",function(){var a;x("unload");if(Z){do a=new Date;while(a.getTimeAlias()<Z)}},!1);(function(){var a;n.addEventListener?h(n,"DOMContentLoaded",function u(){n.removeEventListener("DOMContentLoaded",u,!1);s()}):n.attachEvent&&(n.attachEvent("onreadystatechange",function p(){"complete"===
n.readyState&&(n.detachEvent("onreadystatechange",p),s())}),n.documentElement.doScroll&&l===l.top&&function aa(){if(!ja){try{n.documentElement.doScroll("left")}catch(a){setTimeout(aa,0);return}s()}}());/WebKit/.test(H.userAgent)&&(a=setInterval(function(){if(ja||/loaded|complete/.test(n.readyState))clearInterval(a),s()},10));h(l,"load",s,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;ea=new ka;var pa={setTrackerUrl:1,setAPIUrl:1,setUserId:1,setSiteId:1,disableCookies:1,enableLinkTracking:1},
$;for(L=0;L<_paqAnts.length;L++)$=_paqAnts[L][0],pa[$]&&(f(_paqAnts[L]),delete _paqAnts[L],1<pa[$]&&void 0!==console&&(console&&console.error)&&console.error("The method "+$+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),pa[$]++);for(L=0;L<_paqAnts.length;L++)_paqAnts[L]&&f(_paqAnts[L]);_paqAnts=new function(){return{push:f}};
oa={addPlugin:function(a,b){qa[a]=b},getTracker:function(a,c){b(c)||(c=this.getAsyncTracker().getSiteId());b(a)||(a=this.getAsyncTracker().getTrackerUrl());return new ka(a,c)},getAsyncTracker:function(){return ea}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return oa});return oa}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=PiwikAnts)})();
"function"!==typeof piwik_log&&(piwik_log=function(b,d,c,g){function f(b){try{return eval("piwik_"+b)}catch(c){}}var h=PiwikAnts.getTracker(c,d);h.setDocumentTitle(b);h.setCustomData(g);(b=f("tracker_pause"))&&h.setLinkTrackingTimer(b);(b=f("download_extensions"))&&h.setDownloadExtensions(b);(b=f("hosts_alias"))&&h.setDomains(b);(b=f("ignore_classes"))&&h.setIgnoreClasses(b);h.trackPageView();f("install_tracker")&&(piwik_track=function(b,c,d,f){h.setSiteId(c);h.setTrackerUrl(d);h.trackLink(b,f)},
h.enableLinkTracking())});function ants_isIE(){var b=navigator.userAgent.toLowerCase();return-1!=b.indexOf("msie")?parseInt(b.split("msie")[1]):!1}if(9==ants_isIE())try{_antsLoadScript("//st-a.anthill.vn/v2/ie9.js")}catch(ex){}function b64ToUint6(b){return 64<b&&91>b?b-65:96<b&&123>b?b-71:47<b&&58>b?b+4:43===b?62:47===b?63:0}
function base64DecToArr(b,d){try{for(var c=b.replace(/[^A-Za-z0-9\+\/]/g,""),g=c.length,f=d?Math.ceil((3*g+1>>2)/d)*d:3*g+1>>2,h=new Uint8Array(f),x,s,v=0,S=0,Q=0;Q<g;Q++)if(s=Q&3,v|=b64ToUint6(c.charCodeAt(Q))<<6*(3-s),3===s||1===g-Q){for(x=0;3>x&&S<f;x++,S++)h[S]=v>>>(16>>>x&24)&255;v=0}return h}catch(q){return""}}function uint6ToB64(b){return 26>b?b+65:52>b?b+71:62>b?b-4:62===b?43:63===b?47:65}
function base64EncArr(b){for(var d=2,c="",g=b.length,f=0,h=0;h<g;h++)if(d=h%3,0<h&&0===4*h/3%76&&(c+="\r\n"),f|=b[h]<<(16>>>d&24),2===d||1===b.length-h)c+=String.fromCharCode(uint6ToB64(f>>>18&63),uint6ToB64(f>>>12&63),uint6ToB64(f>>>6&63),uint6ToB64(f&63)),f=0;return c.substr(0,c.length-2+d)+(2===d?"":1===d?"\x3d":"\x3d\x3d")}
function UTF8ArrToStr(b){for(var d="",c,g=b.length,f=0;f<g;f++)c=b[f],d+=String.fromCharCode(251<c&&254>c&&f+5<g?1073741824*(c-252)+(b[++f]-128<<24)+(b[++f]-128<<18)+(b[++f]-128<<12)+(b[++f]-128<<6)+b[++f]-128:247<c&&252>c&&f+4<g?(c-248<<24)+(b[++f]-128<<18)+(b[++f]-128<<12)+(b[++f]-128<<6)+b[++f]-128:239<c&&248>c&&f+3<g?(c-240<<18)+(b[++f]-128<<12)+(b[++f]-128<<6)+b[++f]-128:223<c&&240>c&&f+2<g?(c-224<<12)+(b[++f]-128<<6)+b[++f]-128:191<c&&224>c&&f+1<g?(c-192<<6)+b[++f]-128:c);return d}
function strToUTF8Arr(b){var d,c;d=b.length;for(var g=0,f=0;f<d;f++)c=b.charCodeAt(f),g+=128>c?1:2048>c?2:65536>c?3:2097152>c?4:67108864>c?5:6;d=new Uint8Array(g);for(var h=f=0;f<g;h++)c=b.charCodeAt(h),128>c?d[f++]=c:(2048>c?d[f++]=192+(c>>>6):(65536>c?d[f++]=224+(c>>>12):(2097152>c?d[f++]=240+(c>>>18):(67108864>c?d[f++]=248+(c>>>24):(d[f++]=252+(c>>>30),d[f++]=128+(c>>>24&63)),d[f++]=128+(c>>>18&63)),d[f++]=128+(c>>>12&63)),d[f++]=128+(c>>>6&63)),d[f++]=128+(c&63));return d}
function ants_encryptBase64(b){if(9==ants_isIE())return b;b=strToUTF8Arr(b);return base64EncArr(b)}function ants_decryptBase64(b){if(9==ants_isIE())return b;b=base64DecToArr(b);return UTF8ArrToStr(b)};var LOG_TRACKING_URL="//a.ants.vn",STATIC_FILE_URL="//st-a.anthill.vn",AI_VERSION="v1.0",ENV="prod";"sandbox"==ENV&&(LOG_TRACKING_URL="//sandbox-a.ants.vn",STATIC_FILE_URL="//sandbox-st-a.anthill.vn");var _iants=_iants||[],aiFunction=aiFunction||{};window.aiFunction.randomString=function(b,d){d=d||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";for(var c="",g=0;g<b;g++)var f=Math.floor(Math.random()*d.length),c=c+d.substring(f,f+1);return c};
window.aiFunction.setCookie=function(b,d,c,g,f,h){var x;void 0!=c&&(x=new Date,x.setTime(x.getTime()+c));var s=d+"";isNaN(d)&&(s=window.encodeURIComponent(d));b=b+"\x3d"+s+(c?";expires\x3d"+x.toGMTString():"")+";path\x3d"+(g||"/")+(f?";domain\x3d"+f:"")+(h?";secure":"");document.cookie=b};window.aiFunction.getCookie=function(b){return(cookieMatch=RegExp("(^|;)[ ]*"+b+"\x3d([^;]*)").exec(document.cookie))?window.decodeURIComponent(cookieMatch[2]):0};
window.aiFunction.getURLParameter=function(b){for(var d=window.location.search.substring(1).split("\x26"),c=0;c<d.length;c++){var g=d[c].split("\x3d");if(g[0]==b)return g[1]}try{var f=window.location.href;if(0<f.indexOf("?utm"))for(d=f.substring(f.indexOf("?utm")+1).split("\x26"),c=0;c<d.length;c++)if(g=d[c].split("\x3d"),g[0]==b)return g[1]}catch(h){}return""};
window.aiFunction.getReferrer=function(){var b="";try{b=window.top.document.referrer}catch(d){if(window.parent)try{b=window.parent.document.referrer}catch(c){b=""}}""===b&&(b=document.referrer);return b};window.aiFunction.getHostName=function(b){var d=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b);return d?d[1]:b};
window.aiFunction.getReferrerDomain=function(b){b="";var d=window.aiFunction.getReferrer();void 0!=d&&(""!=d&&0<d.length)&&(d=window.aiFunction.getHostName(d),void 0!=d&&""!=d&&(b=d.replace("www.","")));return b};_ants_ecommerceItems=[];var ai_sent_sites;if("undefined"==typeof ai_sent_sites||null==ai_sent_sites)ai_sent_sites=[];
function checkSendLogProfile(b,d){if(d||0>=b.socialType)return!0;var c=!0;try{var g=_ea_get_tup(b.socialType);g==b.socialId+"-"+b.socialType&&""!=g&&(c=!1)}catch(f){}return c}
function _antsGetDefaultCookieDomain(){for(var b="net com edu org gov biz info".split(" "),d=0,c=b.length;d<c;++d)b.push(b[d]+"\\.vn");b.push("vn");b.push("us");var b=RegExp("(\\.?[^.]+\\.("+b.join("|")+")$)"),b=document.domain.match(b),g;null!==b?g=b[1]:(b=document.domain.match(/(\.?[^.]+\.?[^.]+$)/),null!==b&&(g=b[1]));"."==g[0]&&(g=g.substr(1));return g}
function iantsGetPageview(){if(null!=("undefined"!==typeof window&&null!==window?window._antspv:void 0))return"undefined"!==typeof window&&null!==window?window._antspv:void 0;"undefined"!==typeof window&&null!==window&&(window._antspv=(new Date).getTime());return"undefined"!==typeof window&&null!==window?window._antspv:void 0}
var _ea_get_utm=function(){var b={source:"",medium:"",campaign:"",content:"",term:"",type:"",checksum:""};try{var d=!0,c=window.aiFunction.getCookie("_ants_utm_v2");if(void 0==c||""==c)c=window.aiFunction.getCookie("_ants_utm"),d=!1;if(void 0!=c&&""!=c){var g=ants_decryptBase64(c);if(void 0!=g&&""!=g){var b=JSON2.parse(g),f=_ea_utm_checksum(b);if(d&&f==b.checksum)return b}}if("undefined"!==typeof Storage)try{if(c=window.localStorage._ants_utm_v2,void 0!=c&&""!=c){g=ants_decryptBase64(c);if(void 0!=
g&&""!=g&&(b=JSON2.parse(c),f=_ea_utm_checksum(b),d&&f!=b.checksum))return b={source:"",medium:"",campaign:"",content:"",term:"",type:"",checksum:""};var h=b.time+15552E6;if((new Date).getTime()>h)window.localStorage._ants_utm_v2="";else return window.aiFunction.setCookie("_ants_utm_v2",c,15552E6,"/","",0),b}}catch(x){}}catch(s){}return b};
function AdxAnalytics(){var b=document,d=window,c=d.encodeURIComponent,g=d.decodeURIComponent,f=LOG_TRACKING_URL;this.setCookie=function(d,f,g,h,D,F){var q;g&&(q=new Date,q.setTime(q.getTime()+g));b.cookie=d+"\x3d"+c(f)+(g?";expires\x3d"+q.toGMTString():"")+";path\x3d"+(h||"/")+(D?";domain\x3d"+D:"")+(F?";secure":"")};this.getCookie=function(c){return(cookieMatch=RegExp("(^|;)[ ]*"+c+"\x3d([^;]*)").exec(b.cookie))?g(cookieMatch[2]):0};var h=new Date,x,s=0,v,S=this.getCookie("au_aid")||0,Q=0,q="";
this.logData=function(b){try{if("undefined"!=typeof ai_sent_sites&&-1<ai_sent_sites.indexOf(b))return!1;v=this.getAntsConfig("setCookieDomain");""===v&&(v=_antsGetDefaultCookieDomain());_paqAnts.push(["setDocumentTitle",document.title]);_paqAnts.push(["setCookieDomain","*."+v]);_paqAnts.push(["setTrackerUrl",f+"/get"]);_paqAnts.push(["setSiteId",b]);var c=iantsGetPageview(),d,g,D,q,s,x;g=this.getCookie("an_session");d=this.getCookie("au_aid");x=this.getCookie("dgs");if("undefined"!==typeof Storage)try{0===
g&&(g=window.localStorage.an_session),0===d&&(d=window.localStorage.au_aid),D=window.localStorage.pv,q=window.localStorage.t1,s=window.localStorage.t2,null===q&&(q=0),null===s&&(s=0)}catch(fa){}_paqAnts.push(["setCustomVariable","2","au_aid_bk",d,"page"]);_paqAnts.push(["setCustomVariable","3","an_session",g,"page"]);_paqAnts.push(["setCustomVariable","4","pv",D,"page"]);_paqAnts.push(["setCustomVariable","8","t1",q,"page"]);_paqAnts.push(["setCustomVariable","9","t2",s,"page"]);_paqAnts.push(["setCustomVariable",
"10","time_diff",s-q,"page"]);_paqAnts.push(["setCustomVariable","11","dgs",x,"page"]);_paqAnts.push(["setCustomVariable","12","antspv",c,"page"]);var r=_ea_get_utm();void 0!=r.source&&""!=r.source&&_paqAnts.push(["setCustomVariable","13","utm_source",r.source,"page"]);void 0!=r.campaign&&""!=r.campaign&&_paqAnts.push(["setCustomVariable","14","utm_campaign",r.campaign,"page"]);void 0!=r.medium&&""!=r.medium&&_paqAnts.push(["setCustomVariable","15","utm_medium",r.medium,"page"]);void 0!=r.content&&
""!=r.content&&_paqAnts.push(["setCustomVariable","16","utm_content",r.content,"page"]);void 0!=r.term&&""!=r.term&&_paqAnts.push(["setCustomVariable","17","utm_term",r.term,"page"]);void 0!=r.term&&""!=r.term&&_paqAnts.push(["setCustomVariable","18","utm_type",r.type,"page"]);_paqAnts.push(["setCustomVariable","5","des","","page"]);var z=this.getMeta("adx:keywords");try{if(!1==z||""==z)0<window.location.href.indexOf("q\x3d")?z=window.aiFunction.getURLParameter("q"):0<window.location.href.indexOf("search\x3d")?
z=window.aiFunction.getURLParameter("search"):0<window.location.href.indexOf("query\x3d")&&(z=window.aiFunction.getURLParameter("query"));if(!1==z||void 0==z||""==z)z=this.getMeta("keywords")}catch(Q){}null!=z&&""!=z&&(z=z.substring(0,150),_paqAnts.push(["setCustomVariable","6","keywords",z,"page"]));var Z=this.getCookie("au_aid");void 0==Z&&(Z=this.getCookie("an_aid"));_paqAnts.push(["setCustomVariable","7","au_aid",Z,"page"]);var S=this.getMeta("adx:sections");!1!=S&&_paqAnts.push(["setCustomVariable",
"50","sections",S,"page"]);var n=this.getMeta("adx:objects");!1!=n&&_paqAnts.push(["setCustomVariable","51","objects",n,"page"]);var H=this.getMeta("adx:authors");!1!=H&&_paqAnts.push(["setCustomVariable","52","authors",H,"page"]);var xa=this.getMeta("adx:users");!1!=xa&&_paqAnts.push(["setCustomVariable","53","users",xa,"page"]);var l=this.getMeta("adx:cuid");!1!=l&&_paqAnts.push(["setCustomVariable","54","cuid",l,"page"]);PiwikAnts.getAsyncTracker().trackPageView();"undefined"!=typeof ai_sent_sites&&
ai_sent_sites.push(b);if("undefined"!==typeof Storage)try{window.localStorage.t1=h.getTime()}catch(ia){}}catch(ja){}};this.getAntsConfig=function(b){if("undefined"===typeof _iants)return"";for(i=0;i<_iants.length;i++)if(_iants[i][0]===b)return _iants[i][1];return""};this.incrCountTimeTrack=function(b){s+=b};this.getMydomain=function(){return v};this.getCountTimeTrack=function(){return s};this.getTrackingBaseUrl=function(){return f};this.getStartTime=function(){return h};this.getPageviewId=function(){return x};
this.setPageviewId=function(b){x=b};this.setVisitorId=function(b){S=b};this.getVisitorId=function(){return S};this.setGlobalId=function(b){Q=b};this.getGlobalId=function(){return Q};this.setClientIP=function(b){q=b};this.getClientIP=function(){return q};this.loadScript=function(b,c){var d=document.getElementsByTagName("head")[0],f=document.createElement("script");f.type="text/javascript";f.src=b;f.async=!0;f.onreadystatechange=c;f.onload=c;d.appendChild(f)};this.getMeta=function(b){var c=document.getElementsByTagName("meta");
if(0<c.length)for(var d=0;d<c.length;d++)if(null!=c[d].getAttribute("name")&&c[d].getAttribute("name").toLowerCase()==b.toLowerCase())return c[d].getAttribute("content");return!1};this.trackingGoalVisit=function(b,c,d){var g=adx_analytic.getPageviewId();"undefined"===typeof g&&"undefined"!==typeof pv_id&&(g=pv_id);if("undefined"!==typeof b&&"undefined"!==typeof g&&"visit_page"===d&&adx_analytic.currGoal!==b+":"+g){var h=_ea_get_utm();d={goal_type:d?d:"visit_page",pv_id:g,source:h.source,campaign:h.campaign,
medium:h.medium,content:h.content,term:h.term};_paqAnts.push(["setTrackerUrl",f+"/goal"]);_paqAnts.push(["trackGoal",b,c?c:1,d]);adx_analytic.currGoal=b+":"+g}};this.trackingGoal=function(b,c,d){var g=adx_analytic.getPageviewId();"undefined"===typeof g&&"undefined"!==typeof pv_id&&(g=pv_id);if("undefined"!==typeof b&&"undefined"!==typeof g&&"visit_page"!==d&&adx_analytic.currGoal!==b+":"+g){var h=_ea_get_utm();d={goal_type:d?d:"event",pv_id:g,source:h.source,campaign:h.campaign,medium:h.medium,content:h.content,
term:h.term};_paqAnts.push(["setTrackerUrl",f+"/goal"]);_paqAnts.push(["trackGoal",b,c?c:1,d]);adx_analytic.currGoal=b+":"+g}};this.trackingFormVisit=function(b,c){var d=adx_analytic.getPageviewId();"undefined"===typeof d&&"undefined"!==typeof pv_id&&(d=pv_id);if("undefined"!==typeof b&&"undefined"!==typeof d&&"visit_page"===c&&""!=b){var g=void 0!=b.description?b.description:"";"undefined"==g&&(g="");g={name:void 0!=b.name?b.name:"",phone:void 0!=b.phone?b.phone:"",email:void 0!=b.email?b.email:
"",gender:void 0!=b.gender?b.gender:"",birthday:void 0!=b.birthday?b.birthday:"",socialId:void 0!=b.socialId?b.socialId:0,socialType:void 0!=b.socialType?b.socialType:0,address:void 0!=b.address?b.address:"",description:g,others:void 0!=b.others?b.others:"",app:b.app};""!=g.name&&(g=ants_encryptBase64(JSON2.stringify(g)),b={us_info:g,pv_id:d,encrypt:"true"},_paqAnts.push(["setTrackerUrl",f+"/goal"]),_paqAnts.push(["trackGoal","uptrack",1,b]))}};this.trackingEvent=function(b,c,d){var g=adx_analytic.getPageviewId();
"undefined"===typeof g&&"undefined"!==typeof pv_id&&(g=pv_id);"undefined"!==typeof g&&"tup"===b&&(b=void 0!=c.description?c.description:"","undefined"==b&&(b=""),c={name:void 0!=c.name?c.name:"",phone:void 0!=c.phone?c.phone:"",email:void 0!=c.email?c.email:"",gender:void 0!=c.gender?c.gender:"",birthday:void 0!=c.birthday?c.birthday:"",socialId:void 0!=c.socialId?c.socialId:0,socialType:void 0!=c.socialType?c.socialType:0,address:void 0!=c.address?c.address:"",description:b,others:void 0!=c.others?
c.others:"",app:c.app},checkSendLogProfile(c,d)&&""!=c.name&&(_ea_save_tup(c.socialId,c.socialType),c=ants_encryptBase64(JSON2.stringify(c)),c={us_info:c,pv_id:g,encrypt:"true"},_paqAnts.push(["setTrackerUrl",f+"/goal"]),_paqAnts.push(["trackGoal","uptrack",1,c])))};this.trackingEcommerce=function(b,c,d,g,h,q,s,v){var x=adx_analytic.getPageviewId();if("undefined"!==typeof b&&"undefined"!==typeof x){if(0<_ants_ecommerceItems.length)for(var r=0;r<_ants_ecommerceItems.length;r++){var z=_ants_ecommerceItems[r];
_paqAnts.push(["addEcommerceItem",void 0!=z.id?z.id:"",void 0!=z.name?z.name:"",void 0!=z.category?z.category:"",void 0!=z.price?z.price:"",void 0!=z.quantity?z.quantity:1])}adx_analytic.currEcommerce!==c+":"+x&&(d=void 0!=d?d:0,g=void 0!=g?g:0,h=void 0!=h?h:0,q=void 0!=q?q:0,s=void 0!=s?s:0,v=void 0!=v?v:"",r=_ea_get_utm(),v={goal_type:"event",pv_id:x,source:r.source,campaign:r.campaign,medium:r.medium,content:r.content,term:r.term,others:v},_paqAnts.push(["setTrackerUrl",f+"/ecommerce"]),_paqAnts.push(["setCustomData",
v]),_paqAnts.push(["trackEcommerceOrder",b,c,d,g,h,q,s]),adx_analytic.currEcommerce=c+":"+x)}};this.trackingEventBasic=function(b,c,d,g,h,q){var s=adx_analytic.getPageviewId();"undefined"===typeof s&&"undefined"!==typeof pv_id&&(s=pv_id);"undefined"===typeof s||("undefined"===typeof b||""==b||1>=b.length)||(30<b.length&&(b=b.substring(0,30)),"undefined"===typeof c||(""==c||1>=c.length)||(30<c.length&&(c=c.substring(0,30)),"undefined"===typeof d||(""==d||1>=d.length)||(30<d.length&&(d=d.substring(0,
30)),"undefined"===typeof g||0>parseFloat(g)||adx_analytic.currEvent===c+":"+s&&!q||(h={pv_id:s,fieldsObject:h},_paqAnts.push(["setTrackerUrl",f+"/event"]),_paqAnts.push(["trackEvent",b,c,d,g,h]),adx_analytic.currEvent=c+":"+s))))};this.gt=function(b){"undefined"!=typeof ants_callbackData&&ants_callbackData(b,"gt")};this.pt=function(b){"undefined"!=typeof ants_callbackData&&ants_callbackData(b,"pt")};this.evt=function(b){"undefined"!=typeof ants_callbackData&&ants_callbackData(b,"evt")}}
window.onbeforeunload=function(b){try{var d=new Date-adx_analytic.getStartTime();"undefined"!==typeof Storage&&(window.localStorage.pv=window.localStorage.pv.replace(":0",":"+d))}catch(c){}};
var an_session,pv_id,callback_ea=function(b){var d=b.vid,c=b.au_gt,g=b.pvId,f=b.dgs,h=b.services;ants_pvId=b.pvId;an_session=b.an_session;pv_id=b.pvId;adx_analytic.setPageviewId(g);adx_analytic.setVisitorId(d);adx_analytic.setGlobalId(b.globalId);try{void 0!=b.networks&&adx_analytic.setClientIP(b.networks.client_ip)}catch(x){}var g=new Date,s="."+adx_analytic.getMydomain();window.aiFunction.setCookie("an_session",an_session,63072E6,"/",s,0);0===window.aiFunction.getCookie("au_aid")&&window.aiFunction.setCookie("au_aid",
d,63072E6,"/",s,0);"undefined"!==typeof f&&""!==f&&window.aiFunction.setCookie("dgs",f,63072E6,"/",s,0);d=window.aiFunction.getCookie("au_gt");"undefined"!==typeof d&&0!==d&&""!==d||window.aiFunction.setCookie("au_gt",c,63072E6,"/",s,0);"undefined"!==typeof h&&window.aiFunction.setCookie("_ants_services",JSON.stringify(h),63072E6,"/",s,0);"undefined"!==typeof Storage&&(b.vid&&(window.localStorage.au_aid=b.vid),b.pvId&&(window.localStorage.pv=b.pvId+":0"),b.eatv&&(window.localStorage.eatv=b.eatv),
b.an_session&&(window.localStorage.an_session=b.an_session),b.au_gt&&""!=b.au_gt&&(window.localStorage.au_gt=b.au_gt),window.localStorage.t2=g.getTime());adx_analytic.trackingGoalVisit(window._ants_goal_id,window._ants_goal_revenue,window._ants_goal_type);adx_analytic.trackingFormVisit(window._ants_form_data,window._ants_form_type)},adx_analytic=new AdxAnalytics,_ea_loader_function=function(){try{"512041970"===window._siteId?"undefined"!=typeof FLAG_SEND_LOG&&FLAG_SEND_LOG||(adx_analytic.logData(window._siteId,
1),FLAG_SEND_LOG=!0):adx_analytic.logData(window._siteId,1)}catch(b){}};_ea_loader_function();
var _antsLoadScript=function(b){var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=b;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(d,b)},_antsLoadServices=function(){try{var b=window.aiFunction.getCookie("_ants_services");if(void 0!=b&&""!=b){var d=JSON.parse(b),c=b=-1,g=-1;void 0!=d&&(b=d.indexOf("dfp"),c=d.indexOf("wap"),g=d.indexOf("cuid"));(0<=b||0<=c||0<=g)&&_antsLoadScript(STATIC_FILE_URL+"/ais.js")}}catch(f){}};_antsLoadServices();
var _ea_trackfb_detail=function(){try{"513863818"===window._siteId||"528667588"===window._siteId||"529216172"===window._siteId||"529216174"===window._siteId||"529423847"===window._siteId||"529423826"===window._siteId||"513588738"===window._siteId||"514627802"===window._siteId||"513588735"===window._siteId||"515321670"===window._siteId||"513588711"===window._siteId||"530049281"===window._siteId?_antsLoadScript(STATIC_FILE_URL+"/fb.js"):"554926188"!==window._siteId&&_antsLoadScript(STATIC_FILE_URL+
"/is.js")}catch(b){}},_ea_trackfb=function(){"515584286"===window._siteId?"undefined"!=typeof FLAG_FB&&FLAG_FB||(_ea_trackfb_detail(),FLAG_FB=!0):_ea_trackfb_detail()};_ea_trackfb();
var _ea_utm_checksum=function(b){try{return ants_encryptBase64(b.source+"-"+b.medium+"-"+b.campaign+"-"+b.time)}catch(d){}return""},_ea_save_utm=function(){try{var b="",d=!1,c=window.location.href;if(0<c.indexOf("utm_")){var g={source:window.aiFunction.getURLParameter("utm_source"),medium:window.aiFunction.getURLParameter("utm_medium"),campaign:window.aiFunction.getURLParameter("utm_campaign"),content:window.aiFunction.getURLParameter("utm_content"),term:window.aiFunction.getURLParameter("utm_term"),
type:"direct",time:(new Date).getTime(),checksum:""};g.checksum=_ea_utm_checksum(g);b=JSON2.stringify(g);d=!0}else if(0<c.indexOf("code_chanel"))g={source:window.aiFunction.getURLParameter("code_chanel"),medium:"",campaign:window.aiFunction.getURLParameter("id_campaign"),content:window.aiFunction.getURLParameter("id_landingpage"),term:window.aiFunction.getURLParameter("id"),type:"direct",time:(new Date).getTime(),checksum:""},g.checksum=_ea_utm_checksum(g),b=JSON2.stringify(g),d=!0;else{var f=window.aiFunction.getReferrerDomain(),
h=_antsGetDefaultCookieDomain(),x=_ea_get_utm();void 0!=f&&""!=f&&void 0!=h&&""!=h&&0>f.indexOf(h)||""==x.source&&void 0!=f&&""!=f?(g={source:f,medium:"",campaign:"",content:"",term:"",type:"refferrer",time:(new Date).getTime(),checksum:""},d=!0,g.checksum=_ea_utm_checksum(g),b=JSON2.stringify(g)):""!=f||(void 0==h||""==h||""!=x.source&&"refferrer"!=x.type)||(b="",d=!0)}if(d){var s=ants_encryptBase64(b);window.aiFunction.setCookie("_ants_utm_v2",s,15552E6,"/","",0);window.aiFunction.setCookie("_ants_utm",
"",0,"/","",0);"undefined"!==typeof Storage&&(d||b)&&(window.localStorage._ants_utm_v2=s,window.localStorage.removeItem("_ants_utm"))}}catch(v){}};_ea_save_utm();
var _ea_save_tup=function(b,d){try{if(void 0!=b&&""!=b&&0<d){var c={checksum:b+"-"+d,time:(new Date).getTime()},g=JSON2.stringify(c);key="_ants_tup_"+d;window.aiFunction.setCookie(key,g,864E5,"/","",0);"undefined"!==typeof Storage&&key&&localStorage.setItem(key,g)}}catch(f){}},_ea_get_tup=function(b){var d="";try{if(0>=b)return d;b="_ants_tup_"+b;var c="",g=window.aiFunction.getCookie(b);if(void 0!=g&&""!=g)c=JSON2.parse(g);else if("undefined"!==typeof Storage)try{if(g=localStorage.getItem(b),void 0!=
g&&""!=g){var c=JSON2.parse(g),f=c.time+864E5;(new Date).getTime()>f&&localStorage.setItem(b,"")}}catch(h){}""!=c&&(d=c.checksum)}catch(x){}return d};