!function(g){var I="//st-au.ants.vn/proxy-conversion.html",y,A,k,D,E,F,G,H,J={}.hasOwnProperty,K=[].slice,L=function(c,f){return function(){return c.apply(f,arguments)}};k={base64:{_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(c){var f,a,b,d,e,m,g,r;r="";g=0;for(c=k.base64._utf8_encode(c);g<c.length;)f=c.charCodeAt(g++),a=c.charCodeAt(g++),b=c.charCodeAt(g++),d=f>>2,f=(f&3)<<4|a>>4,e=(a&15)<<2|b>>6,m=b&63,isNaN(a)?e=m=64:isNaN(b)&&(m=64),r=r+this._keyStr.charAt(d)+
this._keyStr.charAt(f)+this._keyStr.charAt(e)+this._keyStr.charAt(m);return r},_utf8_encode:function(c){var f,a,b;c=c.replace(/\r\n/g,"\n");b="";for(a=0;a<c.length;)f=c.charCodeAt(a),128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128)),a++;return b}},appendScript:function(c,f){var a,b;b=document.createElement("span");b.className="span-append";b.style.display="none";
c.appendChild(b);a=document.createElement("script");null!=(null!=f?f.text:void 0)?a.text=f.text:(a.src=f.src,a.async=1);return b.parentNode.replaceChild(a,b)},getScriptsFromConversion:function(c,f){return k.json(""+c+"?conversion_id="+f,function(a){var b,d;if(0<(null!=a?null!=(d=a.scripts)?d.length:void 0:void 0))return b=document.createElement("div"),b.className="script-ants-append",b.style.display="none",document.body.appendChild(b),null!=a?a.scripts.forEach(function(a){return k.appendScript(b,a)}):
void 0})},sha1:function(c){var f,a,b,d,e,m,v,r,k,l,n,q,p,h,t,s,u;t=function(a,b){return a<<b|a>>>32-b};p=function(a){var b,d;c="";for(b=7;0<=b;)d=a>>>4*b&15,c+=d.toString(16),b--;return c};f=h=q=void 0;n=[];m=1732584193;v=4023233417;r=2562383102;k=271733878;l=3285377520;a=s=e=d=b=a=f=void 0;u=[];c=unescape(g.encodeURIComponent(c));a=c.length;for(h=0;h<a-3;)f=c.charCodeAt(h)<<24|c.charCodeAt(h+1)<<16|c.charCodeAt(h+2)<<8|c.charCodeAt(h+3),u.push(f),h+=4;switch(a&3){case 0:h=2147483648;break;case 1:h=
c.charCodeAt(a-1)<<24|8388608;break;case 2:h=c.charCodeAt(a-2)<<24|c.charCodeAt(a-1)<<16|32768;break;case 3:h=c.charCodeAt(a-3)<<24|c.charCodeAt(a-2)<<16|c.charCodeAt(a-1)<<8|128}for(u.push(h);14!==(u.length&15);)u.push(0);u.push(a>>>29);u.push(a<<3&4294967295);for(q=0;q<u.length;){for(h=0;16>h;)n[h]=u[q+h],h++;for(h=16;79>=h;)n[h]=t(n[h-3]^n[h-8]^n[h-14]^n[h-16],1),h++;f=m;a=v;b=r;d=k;e=l;for(h=0;19>=h;)s=t(f,5)+(a&b|~a&d)+e+n[h]+1518500249&4294967295,e=d,d=b,b=t(a,30),a=f,f=s,h++;for(h=20;39>=h;)s=
t(f,5)+(a^b^d)+e+n[h]+1859775393&4294967295,e=d,d=b,b=t(a,30),a=f,f=s,h++;for(h=40;59>=h;)s=t(f,5)+(a&b|a&d|b&d)+e+n[h]+2400959708&4294967295,e=d,d=b,b=t(a,30),a=f,f=s,h++;for(h=60;79>=h;)s=t(f,5)+(a^b^d)+e+n[h]+3395469782&4294967295,e=d,d=b,b=t(a,30),a=f,f=s,h++;m=m+f&4294967295;v=v+a&4294967295;r=r+b&4294967295;k=k+d&4294967295;l=l+e&4294967295;q+=16}s=p(m)+p(v)+p(r)+p(k)+p(l);return s.toLowerCase()},objectKeys:function(c){var f,a;a=[];for(f in c)J.call(c,f)&&a.push(f);return a},arrayEach:function(c,
f){var a,b,d,e,m;if(null!=Array.prototype.forEach)return Array.prototype.forEach.call(c,f);m=[];a=d=0;for(e=c.length;d<e;a=++d)b=c[a],m.push(f.call(c,b,a,c));return m},isArray:function(c){return"[object Array]"===Object.prototype.toString.call(c)},each:function(c,f){var a;if(c){if(k.isArray(c))return k.arrayEach(c,f);a=this.objectKeys(c);return k.arrayEach(a,function(a){return f.call(c,c[a],a,c)})}},map:function(c,f){var a;a=[];k.each(c,function(b,d){return a.push(f.call(c,b,d,c))});return a},filter:function(c,
f){var a;a=[];k.each(c,function(b,d){if(f.call(c,b,d,c))return a.push(b)});return a},extend:function(){var c,f,a,b,d,e,m;b=arguments[0];a=2<=arguments.length?K.call(arguments,1):[];b=b||{};e=0;for(m=a.length;e<m;e++)for(c in f=a[e],f)d=f[c],b[c]=d;return b},nextTick:function(c){return k.delay(0,c)},delay:function(c,f){try{return setTimeout(f,c)}catch(a){}},debounce:function(c,f){var a;a=null;return function(){var b,d;d=this;b=arguments_;clearTimeout(a);return a=setTimeout(function(){return c.apply(d,
b)},f)}},json:function(c,f,a){var b,d;try{return"function"===typeof f&&(a=f,f={}),b=function(){var b;if(4===d.readyState&&200===d.status){b=d.responseText;try{return b=JSON.parse(b)}catch(e){}finally{a(b)}}},d=new XMLHttpRequest,d.open("GET",c,!0),d.withCredentials=!0===f.credentials,d.onreadystatechange=b,d.send()}catch(e){}},queue:function(c){var f,a,b,d,e,m,g,r,k,l,n,q,p;n=[].slice;k=void 0;p=[];l=f=q=0;r=void 0;e=null;b=function(){};a=void 0;c||(c=Infinity);g=function(){for(var a,b,e;r=q<p.length&&
f<c;)b=q++,e=p[b],a=n.call(e,1),a.push(d(b)),++f,e[0].apply(null,a)};d=function(a){return function(b,d){--f;null==e&&(null!=d?(e=d,q=l=NaN,m()):(p[a]=b,--l?r||g():m()))}};m=function(){null!=e?b(e):a?b(e,p):b.apply(null,[e].concat(p))};return k={defer:function(){e||(p.push(arguments),++l,g());return k},await:function(d){b=d;a=!1;l||m();return k},awaitAll:function(d){b=d;a=!0;l||m();return k}}}};y=function(){function c(){this.syncInfo=L(this.syncInfo,this);var a,b,d=this;this.has=Object.prototype.hasOwnProperty;
this.queueEvents=k.queue();this.isSyncInfo=!1;this.data={};this.queue=[];this.event=[];this.transactions={};this.locals={};this.locals.isGDN=!1;this.locals.hostname=this.getDomain(g.location.href);this.locals.hostRerfer=this.getDomain(document.referrer);this.locals.isSameHost=this.locals.hostname===this.locals.hostRerfer;this.locals.refer=0;this.locals.internal=0;this.locals.utmSource={};this.instance=null;this.proxyStorage=new A;null!=(a=this.proxyStorage)&&null!=(b=a.iframe)&&(b.onload=function(){return d.syncInfo()})}
var f;c.getInstance=function(){this.isSyncInfo||(this.instance=function(a,b,d){d.prototype=a.prototype;d=new d;a=a.apply(d,b);return Object(a)===a?a:d}(this,arguments,function(){}));return this.instance};c.prototype.setData=function(a){return this.data[a[1]]=a[2]||""};c.prototype.getData=function(a){return this.data[a]||""};c.prototype.syncInfo=function(a){var b,d,e=this;null==a&&(a=function(){});d="ants_bc_"+this.locals.hostname.replace("www","");this.locals.timeBegin=(new Date).getTime();this.locals.pageView=
{conversion_id:"",products:[],page_type:"",time:0};if("undefined"===typeof b||null===b)b=0;this.queueEvents.defer(function(a){return e.proxyStorage.get("proxyDOMReady",a)});this.queueEvents.defer(function(a){return e.proxyStorage.get("au_aid",a)});this.queueEvents.defer(function(a){return e.proxyStorage.get(d,a)});this.queueEvents.defer(function(a){return e.proxyStorage.get("ad_product",a)});this.queueEvents.defer(function(a){return e.proxyStorage.get("ad_vl",a)});return this.queueEvents.awaitAll(function(a,
b){var d,c,f;e.locals.visitorId=b[1].value||"v";if(""===b[4].value||null==b[4].value)d="//au.ants.vn/get_loc?loc",e.locals.ip&&(d+="&ip-address="+e.locals.ip),k.json(d,function(a){var b;if(a.loc)return a=a.loc,e.locals.ip=a.ip,e.locals.area=JSON.stringify({zone:a.zone,province:a.province,country:a.country}),e.locals.province=a.province,null!=(b=e.proxyStorage)?b.set("ad_vl",a,7776E6):void 0});d=b[2].value||"";e.locals.product=b[3].value;e.locals.sessionId=e.getLocalStorage("ants_ad_ss")||"";e.locals.utmSource=
e.getDataUtmSource();if(!e.locals.isSameHost&&""!==document.referrer||e.locals.isGDN||""===document.referrer)e.locals.refer=1;null!=(null!=(c=e.locals.utmSource)?c.ants_clid:void 0)&&(d=e.locals.utmSource.ants_clid,e.locals.internal=1);e.locals.bc=d;if(""===e.locals.sessionId||null==e.locals.sessionId)e.locals.sessionId=e.getSessionId(),e.setLocalStorage("ants_ad_ss",e.locals.sessionId,18E5);6>(null!=(f=String(e.locals.visitorId))?f.length:void 0)&&(e.locals.visitorId=e.getCookieStorage("au_aid"));if(""===
e.locals.visitorId||null===e.locals.visitorId)return k.json("//au.ants.vn/get_id",{credentials:!0},function(a){var b,d,c;e.locals.visitorId=a.au_aid.toString();e.locals.gender=a.gender;e.locals.visitorIdTimeCreate=a.au_gt;null!=(b=e.proxyStorage)&&b.set("au_aid",e.locals.visitorId,63072E6);e.setLocalStorage("au_aid",e.locals.visitorId,63072E6);null!=(d=e.proxyStorage)&&d.set("au_gt",e.locals.visitorIdTimeCreate,63072E6);null!=(c=e.proxyStorage)&&c.set("ad_vg",e.locals.gender,864E5);if(!e.isSyncInfo)return e.enqueue(),
e.isSyncInfo=!0});if(!e.isSyncInfo)return e.enqueue(),e.isSyncInfo=!0})};c.prototype.getDomain=function(a){a=a.replace(/https?:\/\/(www.)?/i,"");return-1===a.indexOf("/")?a:a.split("/")[0]};c.prototype.getFullTime=function(){var a,b,d,e,c,f;a=new Date;f=a.getFullYear();c=a.getMonth()+1;b=a.getDate();d=a.getHours();e=a.getMinutes();a=a.getSeconds();10>c.length&&(c="0"+c);10>b.length&&(b="0"+b);return f+"-"+c+"-"+b+" "+d+":"+e+":"+a};c.prototype.getDataUtmSource=function(){var a,b,d,e,c;a=g.location.href.match(/(^[^#]*)/)[0].split("?");
a=a[a.length-1];e=a.split("&");b={};a=this.getDomain(document.referrer);b.channel=a;for(d=0;d<e.length;)c=e[d].split("="),null!=c[0]&&null!=c[1]&&(-1<["utm_source","utm_content","utm_campaign","utm_medium","ants_clid"].indexOf(c[0])&&(b[c[0]]=c[1]),-1<["gclid"].indexOf(c[0])&&(this.locals.isGDN=!0)),d++;null!=b.utm_source&&(b.type=1);null!=b.utm_source||this.locals.isSameHost||""===a||(b.utm_source=a,b.type=2);this.locals.isGDN&&null==b.utm_source&&(b.channel="GDN",b.utm_source=b.channel,b.type=1);
if(null!=b.utm_source)return this.setLocalStorage("__antscv_utm",JSON.stringify(b),15552E6),b;try{return JSON.parse(this.getLocalStorage("__antscv_utm"))||{}}catch(f){return{}}};c.prototype.conversion=function(a){if("object"===typeof a&&(this.queue.push(a),null!=(null!=a?a.conversionId:void 0)&&k.getScriptsFromConversion("//d.ants.vn/conversion-script",null!=a?a.conversionId:void 0),this.isSyncInfo))return k.debounce(this.enqueue(),250)};c.prototype.push=function(a){if("object"===typeof a&&(this.queue.push(a),
null!=(null!=a?a.conversionId:void 0)&&k.getScriptsFromConversion("//d.ants.vn/conversion-script",null!=a?a.conversionId:void 0),this.isSyncInfo))return k.debounce(this.enqueue(),250)};c.prototype.trackBeacon=function(){var a;a={siteId:"",date:(new Date).getTime(),session:this.locals.sessionId,type:this.locals.typeConversion,bc:this.locals.bc,refer:this.locals.refer,internal:this.locals.internal,refUrl:encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),url:encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0])};
return this.sendLog(f("//t.ants.vn/a1/rm/track-beacon",a))};c.prototype.enqueue=function(){var a,b,d,e,c,v,r,w,l,n,q,p,h,t,s,u,z,x=this;n=this.queue;null!=g.ants_delay_events&&(n=n.concat(g.ants_delay_events));this.queue=[];g.ants_delay_events=[];if(0<n.length){c=[];r=!1;d=[];b=null;q=0;for(p=n.length;q<p;q++)e=n[q],null!=e.conversionId&&(a=e.customParams||[],d.push.apply(d,a),b=e.conversionId,a={conversion_id:e.conversionId,conversion_language:e.language||"en",conversion_format:e.format||"",conversion_currency:e.currency||
"vnd",conversion_label:e.label||"",custom_params:e.custom_params||[],conversion_value:e.value||"",remarketing_only:e.remarketing_only||!1},c.push(a),""!==this.locals.bc&&!1===a.remarketing_only&&""!==a.conversion_label&&(a.siteId=0,a.visitor=this.locals.visitorId||"v",a.date=(new Date).getTime(),a.bc=this.locals.bc,a.session=this.locals.sessionId,a.type=this.locals.typeConversion,a.refer=this.locals.refer,a.internal=this.locals.internal,a.utm=encodeURI(JSON.stringify(this.locals.utmSource)),a.refUrl=
encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),a.url=encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0]),this.sendLog(f("//t.ants.vn/a1/rm/conversion-list",a))));d=this.matchDynamicInfo(d,g.location.href.match(/(^[^#]*)/)[0]);l=null!=this.locals.product&&"object"===typeof this.locals.product?this.locals.product:{};try{for(w=Object.keys(l),v=0;v<(null!=w?w.length:void 0);)(null!=l?null!=(h=l[w[v]])?h.utime:void 0:void 0)<(new Date).getTime()-2592E6&&null!=l&&delete l[w[v]],v++}catch(B){}d=
k.filter(d,function(a){var d,e,c,f,m,g,h,k;c="__ants_ss_"+(null!=a?a.ecomm_pagetype:void 0);d=(null!=(e=x.cookie.getItem(c))?e.split("|"):void 0)||[];if(("cart"===a.ecomm_pagetype||"purchase"===a.ecomm_pagetype)&&-1!==(null!=d?d.indexOf(a.ecomm_prodid):void 0))return!1;"purchase"===a.ecomm_pagetype&&(r=!0);l[b]=null!=l[b]?l[b]:{};l[b].utime=(new Date).getTime();l[b][a.ecomm_pagetype]=null!=l[b][a.ecomm_pagetype]?l[b][a.ecomm_pagetype]:[];f=l[b][a.ecomm_pagetype].length;e=null!=(m=l[b])?null!=(g=m[a.ecomm_pagetype])?
g.indexOf(a.ecomm_prodid):void 0:void 0;-1!==e&&null!=(h=l[b])&&null!=(k=h[a.ecomm_pagetype])&&k.splice(e,1);l[b][a.ecomm_pagetype].push(a.ecomm_prodid);3<f&&l[b][a.ecomm_pagetype].splice(0,f-3);x.locals.pageView.conversion_id=b;x.locals.pageView.page_type=a.ecomm_pagetype;x.locals.pageView.products.push({product:a.ecomm_prodid,quantity:a.ecomm_quantity});if("cart"===a.ecomm_pagetype||"purchase"===a.ecomm_pagetype)d.push(a.ecomm_prodid),x.cookie.setItem(c,d.join("|"),18E5,"/","."+x.locals.hostname);
return!0});null!=(t=this.proxyStorage)&&t.set("ad_product",l,2592E6);d={antspv:this.getPageview(),siteId:"",pgt:(null!=(s=this.locals)?null!=(u=s.pageView)?u.page_type:void 0:void 0)||"",conversion_id:b,events:encodeURI(JSON.stringify(c)),date:(new Date).getTime(),custom_params:d,session:this.locals.sessionId||"",bc:this.locals.bc,refer:this.locals.refer,internal:this.locals.internal,utm:encodeURI(JSON.stringify(this.locals.utmSource)),refUrl:encodeURIComponent(document.referrer.match(/(^[^#]*)/)[0]),
url:encodeURIComponent(g.location.href.match(/(^[^#]*)/)[0])};try{null!=("undefined"!==typeof g&&null!==g?g.__pLayer:void 0)&&(d.pl=(null!=(z=k.base64)?z.encode(encodeURI(JSON.stringify("undefined"!==typeof g&&null!==g?g.__pLayer:void 0))):void 0)+"PLE")}catch(C){}this.sendLog(f("//t.ants.vn/a1/rm/matching-remarketing",d));r&&(this.sendLog(f("//t.ants.vn/a1/rm/conversion-list",d)),this.setLocalStorage("__antscv_utm","",15552E6));if("v"!==this.locals.visitorId)return this.getUserMarketingList(f("//d.ants.vn/delivery/remarketing-list",
d))}};c.prototype.getPageview=function(){if(null!=("undefined"!==typeof g&&null!==g?g._antspv:void 0))return"undefined"!==typeof g&&null!==g?g._antspv:void 0;"undefined"!==typeof g&&null!==g&&(g._antspv=(new Date).getTime());return"undefined"!==typeof g&&null!==g?g._antspv:void 0};c.prototype.matchDynamicInfo=function(a,b){var d,e,c,f,g,w,l,n,q,p,h,t,s,u,z,x,B,C,y;try{return f=document.domain.replace("www.",""),"lazada.vn"===f&&(g=(null!=(l=document.getElementById("pdtsku"))?l.innerHTML:void 0)||
("undefined"!==typeof e&&null!==e?e.pdt_simplesku:void 0),w=RegExp("<[^>]*>","g"),w.test(g)&&(g=g.replace(w,"")),e=null!=(null!=(n=dataLayer[0])?n.pdt_simplesku:void 0)?dataLayer[0]:dataLayer[1],null!=(null!=e?e.pdt_simplesku:void 0)&&a.push({ecomm_name:((null!=e?e.pdt_name:void 0)||"").replace(/&/g,"-").toLowerCase(),ecomm_brand:((null!=e?e.brand:void 0)||"").replace(/&/g,"-"),ecomm_cate:((null!=e?e.sub_subcategory:void 0)||(null!=e?e.subcategory:void 0)||(null!=e?e.category:void 0)||"").replace(/&/g,
"-"),ecomm_prodid:g,ecomm_pagetype:"product",ecomm_quantity:1,ecomm_totalvalue:null!=e?e.pdt_price:void 0}),d=null!=(null!=(t=dataLayer[0])?null!=(s=t.ecommerce)?s.cart:void 0:void 0)?dataLayer[0]:dataLayer[1],null!=(null!=d?null!=(u=d.ecommerce)?u.cart:void 0:void 0)&&k.each(null!=(z=d.ecommerce)?z.cart:void 0,function(b){return a.push({ecomm_prodid:b.sku,ecomm_pagetype:"cart",ecomm_quantity:b.quantity,ecomm_totalvalue:b.price*b.quantity})}),c=null!=(null!=(x=dataLayer[0])?x.order_items:void 0)?
dataLayer[0]:dataLayer[1],null!=(null!=c?c.order_items:void 0)&&k.each(c.order_items,function(b){return a.push({ecomm_prodid:b.id,ecomm_pagetype:"purchase",ecomm_quantity:b.quantity,ecomm_totalvalue:b.price*b.quantity,ecomm_order_id:"order_id:"+c.order_id+" - order_number:"+c.order_number})})),"deca.vn"===f&&("offerdetail"===(null!=(B=dataLayer[0])?B.dynx_pagetype:void 0)&&a.push({ecomm_prodid:null!=(C=dataLayer[0])?C.productid:void 0,ecomm_pagetype:"product",ecomm_quantity:1,ecomm_totalvalue:null!=
(y=dataLayer[0])?y.dynx_totalvalue:void 0}),"conversionintent"===(null!=(q=dataLayer[0])?q.dynx_pagetype:void 0)&&k.each(dataLayer[0].dynx_itemid,function(b,d){var e,c,f;e=null!=(c=dataLayer[0].prices)?c.toString().split("|"):void 0;c=null!=(f=dataLayer[0].quantities)?f.toString().split("|"):void 0;return a.push({ecomm_prodid:b,ecomm_pagetype:"cart",ecomm_quantity:c[d],ecomm_totalvalue:e[d]*c[d]})}),"conversion"===(null!=(p=dataLayer[0])?p.dynx_pagetype:void 0)&&k.each(null!=(h=dataLayer[0].productid)?
h.split("|"):void 0,function(b,d){var e;e=dataLayer[0].transactionProducts[d];return a.push({ecomm_prodid:b,ecomm_pagetype:"purchase",ecomm_quantity:e.quantity,ecomm_totalvalue:e.price*e.quantity,ecomm_order_id:"order_id:"+dataLayer[0].orderid})})),a}catch(A){return[]}};c.prototype.matchUserMarketingList=function(a){return k.json(a,function(a){})};c.prototype.getUserMarketingList=function(a){var b;return null!=(b=this.proxyStorage)?b.set("ad_rmu",(new Date).getTime()):void 0};f=function(a,b){var d,
e,c,f;d=-1<a.indexOf("?");c=[];for(e in b){f=b[e];try{"string"!==typeof f&&(f=JSON.stringify(f)),c.push(""+e+"="+f)}catch(g){}}return a+(d?"&":"?")+c.join("&")};c.prototype.sendLog=function(a,b){var d;null==b&&(b=function(){});d=new Image(1,1);d.onload=b;return d.src=a};c.prototype.globalize=function(a){var b,d;d=[];for(b in a)a.hasOwnProperty(b)?d.push(g[b]=a[b]):d.push(void 0);return d};c.prototype.getSessionId=function(){var a;a=1E3*new Date+~~(1E3*Math.random());return k.sha1(this.locals.visitorId+
a+g.location.href)};c.prototype.setLocalStorage=function(a,b,d){var e;try{return null!=(e=this.cookie)?e.setItem(a,b,d):void 0}catch(c){}};c.prototype.removeLocalStorage=function(a){var b;try{null!=(b=this.cookie)&&b.removeItem(a)}catch(d){}return ex};c.prototype.getLocalStorage=function(a){var b;try{return null!=(b=this.cookie)?b.getItem(a):void 0}catch(d){}};c.prototype.getCookieStorage=function(a){var b,d,e;try{return b=null!=(d=this.cookie)?d.getItem(a):void 0,6>(null!=(e=String(b))?e.length:
void 0)?this.storage.getItem(a):b}catch(c){}};c.prototype.cookie={getItem:function(a){return a&&this.hasItem(a)?unescape(document.cookie.replace(RegExp("(?:^|.*;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null},setItem:function(a,b,d,e,c,f){var g;e="/";c="."+document.domain.replace("www.","");if(a&&!/^(?:expires|max\-age|path|domain|secure)$/.test(a)){g="";if(d)switch(typeof d){case "number":g="; max-age="+d/1E3;break;case "string":g="; expires="+d;
break;case "object":d.hasOwnProperty("toGMTString")&&(g="; expires="+d.toGMTString())}return document.cookie=escape(a)+"="+escape(b)+g+(c?"; domain="+c:"")+(e?"; path="+e:"")+(f?"; secure":"")}},removeItem:function(a){var b;a&&this.hasItem(a)&&(b=new Date,b.setDate(b.getDate()-1),document.cookie=escape(a)+"=; expires="+b.toGMTString()+"; path=/")},hasItem:function(a){return RegExp("(?:^|;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=").test(document.cookie)}};c.prototype.storage={getItem:function(a){var b,
d,e,c;b={};try{c=JSON.parse(g.localStorage.getItem(a))}catch(f){}d=g.localStorage.getItem("expire-"+a);e=null===d?!1:Number(d)<Date.now();if(""===c||null===c)c=JSON.parse(g.localStorage.getItem(a));null==c||e||(b.value=c);b.expire=d||0;return b},setItem:function(a,b,d){var e,c,f;try{return null!=(e=g.localStorage)&&e.setItem(a,JSON.stringify(b)),null===d||isNaN(d)?null!=(c=g.localStorage)?c.removeItem("expire-"+a):void 0:null!=(f=g.localStorage)?f.setItem("expire-"+a,Date.now()+d):void 0}catch(k){}},
removeItem:function(a){var b;b="expire-"+a;g.localStorage.removeItem(a);return g.localStorage.removeItem(b)},removeExpiredKey:function(a){var b,d,c,f;c=g.localStorage;f=[];for(d in c)b=c[d],/expire\-/.test(d)&&(a>Number(b)?(b=d.substr(7),storage.removeItem(d),f.push(storage.removeItem(b))):f.push(void 0));return f}};return c}();A=function(){function c(){var a;this.$counter=0;this.$callbacks={};this.isSupported()&&(a=this.iframe=document.createElement("iframe"),a.src=I,a.width=0,a.height=0,a.style.display=
"none",this.append(),this.proxyWin=a.contentWindow)}var f;f=g.postMessage&&g.JSON;c.prototype.isSupported=function(){return f};c.prototype.addEventListener=function(a,b,d){a=a===g?g:a[0]||a;return a.addEventListener?(a.addEventListener(b,d,!1),!0):a.attachEvent?a.attachEvent("on"+b,d):!1};c.prototype.onMessage=function(a){return this.addEventListener(g,"message",function(b){var d;try{d=JSON.parse(b.data)}catch(c){d=null}return a(d)})};c.prototype.append=function(){var a,b;if(!this.isSupported())return!1;
a=this.iframe;b=this;document.getElementsByTagName("head")[0].appendChild(a);this.onMessage(function(a){if(a&&"ants-proxy-conversion"===a.$)return b.receiver(a)});return!0};c.prototype.receiver=function(a){var b,d;"proxyDOMReady"===a.event&&(this.instance=!0);d=a.$id;b=this.$callbacks[d];if(d&&b)return k.nextTick(function(){return b(a)}),delete this.$callbacks[d]};c.prototype.send=function(a){a.$="ants-proxy-conversion";return this.proxyWin.postMessage(JSON.stringify(a),"*")};c.prototype.set=function(a,
b,d,c){var f;"function"===typeof d&&(c=d,d=null);f={key:a,value:b,expire:d};if(this.isSupported())return f.action="set",f.$id=++this.$counter,this.$callbacks[f.$id]=c,this.send(f);k.nextTick(function(){return"function"===typeof c?c(f):void 0})};c.prototype.get=function(a,b){var c;if(!this.isSupported())return b({error:"not supported"});c={key:a};if(this.isSupported())return c.action="get",c.$id=++this.$counter,this.$callbacks[c.$id]=b,this.send(c);k.nextTick(function(){return"function"===typeof b?
b(c):void 0})};return c}();null!=(null!=(D=g.ants_analytic)?null!=(E=D[0])?E.conversionId:void 0:void 0)&&(k.getScriptsFromConversion("//d.ants.vn/conversion-script",null!=(F=g.ants_analytic)?null!=(G=F[0])?G.conversionId:void 0:void 0),g.ants_delay_events=g.ants_analytic);void 0===(null!=(H=g.ants_analytic)?H.isSyncInfo:void 0)&&(g.ants_analytic=y.getInstance())}(window);
